### ISSUE TITLE
Hyperlinks on mobile

### ISSUE THREAD

**Issue by xPsychoShyx** [tusing/reddit-ffn-bot#102]
The hyperlinks will not redirect on mobile platforms (or at least the official reddit app).

**Comment by tusing** [comment]
The official Reddit app has some pretty bad issues with Markdown parsing. I'd recommend using another Reddit app - most others have much better Markdown parsing.

**Comment by ethanbreck** [comment]
xPsychoShyx BaconReader is a pretty good Reddit App Alternative.

**Comment by TGNYC** [comment]
I use Slide for Reddit on Android.
