### ISSUE TITLE
Fanfiction bot won't show more than 1 post of fics (6 fics)

### ISSUE THREAD

**Issue by tmarkov** [tusing/reddit-ffn-bot#105]
Lately, I have several cases where the bot shows only of the 6 fics requested in the same post, even though more are requested. It only posts one reply, containing 6 of the fics, and the rest are be forgotten.

For example, here (https://www.reddit.com/r/NarutoFanfiction/comments/829u5d/weekly_fic_request_thread_post_fic_requests_here/dvi15ld/) I requested 47 fics: one post with 25, and one post with 22 requests. Each post was answered with only a single post from the bot, containing 6 of the fics requested. I had to split the requests further into 6-request posts to get the bot to link them all.

Another similar case I have seen here: https://www.reddit.com/r/HPfanfiction/comments/7ymqb6/my_hermione_timetravel_compendium_of_the_last/. Out of all the fics the OP has requested, only 6 are actually linked.

**Comment by tusing** [comment]
Fixed in 2.0.0
