### ISSUE TITLE
[Improvement] Use str.ljust for string formatting

### ISSUE THREAD

**Issue by StuxSoftware** [tusing/reddit-ffn-bot#17]
See documentation here: https://docs.python.org/2/library/stdtypes.html#str.ljust

**Comment by tusing** [comment]
I didn't know these existed!

Where do you think this might be able to use this? I don't recall any particular place where our strings are *too* long.

**Comment by StuxSoftware** [comment]
Pause function

**Comment by tusing** [comment]
Noted. I'll fix this when I get the chance.

**Comment by tusing** [comment]
This issue is fixed in the latest push.
