### ISSUE TITLE
If fanfiction has no image, no data is displayed

### ISSUE THREAD

**Issue by tusing** [tusing/reddit-ffn-bot#24]
For fanfictions with no cover image, no data is displayed.

For example, [this](https://www.fanfiction.net/s/11096853/1/She-Chose-Me) fanfiction doesn't have an image, so things like the word count, etc don't display in the final comment.

This is because the XPaths for the description change depending on the presence of an image.

**Comment by StuxSoftware** [comment]
ˋ//*[@id="profile_top"]/span[last()]ˋfor the metadata?

**Comment by tusing** [comment]
This was fixed in one of the last pushes, though would there be a more pythonic way to implement what I put rather than an if-then statement?

**Comment by StuxSoftware** [comment]
I think in this case it's not about pythonic rathen than being more clean.

**Comment by tusing** [comment]
This is fixed.
