### ISSUE TITLE
More sites

### ISSUE THREAD

**Issue by tusing** [tusing/reddit-ffn-bot#45]
@stuxcrystal  @StuxSoftware I will add [HPFanficArchive](http://www.hpfanficarchive.com/stories/) but I would rather do this myself, as a learning experience, so I probably won't look at any pull requests adding this site unless I ask for help on it. After I'm done, it's open season for pull requests regarding the addition for this site. Just in case you were also planning to do it, since you work *way* faster than I do :smile:

**Comment by StuxSoftware** [comment]
Agreed. Have fun!

**Comment by tusing** [comment]
Thanks! I will.

**Comment by tusing** [comment]
Support for HP Fanfic Archive added and pushed. I wasn't sure how the cache worked, so I didn't implement that. I just started learning regex today, so I had to hardcode a few things for `__str__` in Story. Feel free to make any improvements
