### ISSUE TITLE
[Feature Request] Add semicolon for listing several stories inside single linkffn(...)

### ISSUE THREAD

**Issue by DoorIntoSummer** [tusing/reddit-ffn-bot#55]
So, for instance, instead of 

linkffn(ID01) linkffn(ID02) linkffn(ID03)

you’ll only need to use

linkffn(ID01; ID02; ID03)

**Comment by tusing** [comment]
Hi!

Good idea!
I'll implement this next time I get the chance to. I'm busy this week, but this shouldn't be terribly difficult to implement.

**Comment by StuxSoftware** [comment]
I'm going to implement it. However I'm going for the space character instead of semicolon, since the space character is escaped by "%20" when put in URLs, so we don't have the hassle of providing an escape character.

**Comment by StuxSoftware** [comment]
On second thought -- scratch that, I'm gonna use semicolon too. I just found out they are escaped too.

**Comment by StuxSoftware** [comment]
Feature implementation has just been merged.
Close please.

**Comment by tusing** [comment]
Fixed in latest merge
