### ISSUE TITLE
[Suggestion] Add a develop branch

### ISSUE THREAD

**Issue by StuxSoftware** [tusing/reddit-ffn-bot#70]
The idea behind it is that we can distinguish which version is currently used by the actual bot and which one is the current development snapshot.

It works like this:
Whenever you update the VPS-Version you first merge master with develop and then pull from master.
With this you have a good backup of the currently used version

**Comment by tusing** [comment]
Good idea. Was considering this (actually even made a deployment branch) but completely forgot about it.

**Comment by StuxSoftware** [comment]
But I would make the development branch the secondary one.

**Comment by tusing** [comment]
Right. I should be able to find more time to work on the bot this coming weekend - we can polish the current state of the code, readmes, etc, pull that to the VPS, and then create a development branch.

**Comment by StuxSoftware** [comment]
I would first update the VPS than create the development branch and then start refactoring.

For the decision with the refactoring see #71.
