### ISSUE TITLE
I think we should refactor the codebase of reddit_bot.py

### ISSUE THREAD

**Issue by StuxSoftware** [tusing/reddit-ffn-bot#71]
I think, the codebase of reddit_bot.py grows a little bit large.

So I think, we should be splitting up the file into three parts:
- The part that sets up the reddit bot.
- The reddit-bot itself
- And the part that is actually forming the replies.

This makes it easier to add new things into the bot like
- Use threading to query and send reddit messages
- Handle multiple reddit messages simultaneously

**Comment by tusing** [comment]
A good idea. I agree,

**Comment by StuxSoftware** [comment]
I think you should take a look at #74 
I made a lot of bugfixes.
