### ISSUE TITLE
HPFFA metadata doesn't superscript properly for WIP fics

### ISSUE THREAD

**Issue by tusing** [tusing/reddit-ffn-bot#82]
Issue is due to the fact that parentheses in strings grabbed by metadata end the superscript.

Ways to fix this could be:
* Escape all parentheses in metadata
* Filter out all parentheses when grabbing metadata
* Manually replace ```WIP (Work in Progress)``` with ```WIP```

[Issue can be seen in action here.](https://www.reddit.com/r/HPfanfiction/comments/3ek6ol/request_rpgvideo_game_au/ctfqwj4)

I can not do this at the moment as I am not near my computer.

**Comment by StuxSoftware** [comment]
The problem is the reddit markdown parser failing to escape. There's nothing to be done here except replacing the characters.
