### ISSUE TITLE
Handle (usually accidental) replies to bot's post

### ISSUE THREAD

**Issue by turbinicarpus** [tusing/reddit-ffn-bot#85]
# Steps to Reproduce / Scenario: #

1. User A makes a post with linkffn() or similar directives, triggering the bot's (B) reply with links and summaries.
2. User C intends to reply to A but inadvertently replies to B's post.

# Current behavior: #

C's post is ignored by B (as far as I can tell).

# Suggested behavior: #

Some combination of the following:

* B detects C's reply and sends A a private message with a link to C's post and possibly its summary.
* B detects C's reply and sends C a private message warning them that they've probably replied to the wrong post.

**Comment by StuxSoftware** [comment]
I don't think we ever inteded the users to directly reply to our bots.

**Comment by tusing** [comment]
I don't think this can be implemented... Not yet, anyways. It isnan enhancement but one that requires a lot of thought and time to implement, but for little gain.

It does seem like a bit too much work for what is, essentially, a user error and misunderstanding of how Reddit comments work, and could cause some problems if people genuinely intend to reply to the bot (eg. "Thanks Bot!" or anything else).

The "wontfix" label seems appropriate for now.
