### ISSUE TITLE
[Request Thread] Automate ffnbot!refresh for sufficiently new comments and submissions

### ISSUE THREAD

**Issue by StuxSoftware** [tusing/reddit-ffn-bot#89]
Mentioned Here:
https://www.reddit.com/r/HPfanfiction/comments/3kmijc/ffnbot_request_a_feature/cuynx1g

Description:
Check for edits on sufficiently new comments. (MD5-Hashing comments)?

**Comment by tusing** [comment]
Due to the 2.0.0 paradigm of only using streams and being as stateless as possible I'd rather not do this!
