### ISSUE TITLE
pause() not skippable

### ISSUE THREAD

**Issue by tusing** [tusing/reddit-ffn-bot#9]
pause() in reddit_bot.py is not skippable. Looking for a pythonic way to implement a skippable pause function.

**Comment by StuxSoftware** [comment]
Well you could implement it yourself by using os-dependent functions like msvcrt.kbhit and msvcrt.getch on Windows and select on the stdin-descriptor on unix based systems respectively.
To do that I would split the function off to a new module.

This stack-overflow thread might help:
http://stackoverflow.com/questions/6179537/python-wait-x-secs-for-a-key-and-continue-execution-if-not-pressed

**Comment by StuxSoftware** [comment]
I assume the function works?

**Comment by tusing** [comment]
I'm still working on it - in it's current state it actually doesn't for me. This might be because I'm using git bash through ConEmu?

**Comment by tusing** [comment]
Nevermind - it works! Thank you!
