### ISSUE TITLE
[Converter] New domain

### ISSUE THREAD

**Issue by p0ody** [tusing/reddit-ffn-bot#92]
Hey guys, not sure where to put this so you see it ASAP but, i just realized that my domain & host (http://www.p0ody-files.com/ff_to_ebook/) expire on June 8th (I actually thought it was 6th August :P)

Anyway, im still working on my new version of my site, so i moved the old site to my new domain so you can still use it to (http://ff2ebook.com/old/).

You will just need to change you url in your bot.

Something like http://www.ff2ebook.com/old/ffn-bot/index.php?id=$ficID&source=$site&filetype=$epubORmobi

Cya

**Comment by jimbo644664** [comment]
I'm whipping up a quick PR to add straight into the main version of the bot right now.

**Comment by jimbo644664** [comment]
Alright, just waiting for @tusing to merge it into the current version.

**Comment by tusing** [comment]
Thanks for the help!
