### ISSUE TITLE
Ao3 Author's Name Link

### ISSUE THREAD

**Issue by nilesta** [tusing/reddit-ffn-bot#96]
This appears to only effect Ao3 links.

It's missing the domain.  It's linking only to '/users/rubypop/pseuds/rubypop' (example).  So you end up at a 404.

See: https://www.reddit.com/r/FanFiction/comments/4y9f5f/the_best_fanfiction/d6pg9yu

**Comment by jboros** [comment]
Fix against 1.3 branch.

The guidelines for sending PRs to `bleeding` seem out of date.

**Comment by tusing** [comment]
Thanks for resolving.
